/* Generated By:JJTree: Do not edit this line. BPArguments.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=BP,NODE_EXTENDS=,NODE_FACTORY= */
package effect.bparser;

public class BPArguments extends SimpleNode {
  public BPArguments(int id) {
    super(id);
  }

  public BPArguments(BParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2edbdad296e9039c90caf6aeda89ec3c (do not edit this line) */
