/* Generated By:JavaCC: Do not edit this line. BParserTreeConstants.java Version 4.1 */
package effect.bparser;

public interface BParserTreeConstants
{
  public int JJTCOMPILATIONUNIT = 0;
  public int JJTVOID = 1;
  public int JJTNAME = 2;
  public int JJTLITERAL = 3;
  public int JJTARGUMENTS = 4;
  public int JJTLOCALVARIABLEDECLARATION = 5;
  public int JJTSTATEMENTEXPRESSION = 6;


  public String[] jjtNodeName = {
    "CompilationUnit",
    "void",
    "Name",
    "Literal",
    "Arguments",
    "LocalVariableDeclaration",
    "StatementExpression",
  };
}
/* JavaCC - OriginalChecksum=3a79bf7ccc666e706a6959c744b00950 (do not edit this line) */
