/* Generated By:JavaCC: Do not edit this line. BParserVisitor.java Version 4.1 */
package effect.bparser;

public interface BParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(BPCompilationUnit node, Object data);
  public Object visit(BPName node, Object data);
  public Object visit(BPLiteral node, Object data);
  public Object visit(BPArguments node, Object data);
  public Object visit(BPLocalVariableDeclaration node, Object data);
  public Object visit(BPStatementExpression node, Object data);
}
/* JavaCC - OriginalChecksum=e0c592cf2e79ae453b07a315204bbf2e (do not edit this line) */
