/* Generated By:JJTree: Do not edit this line. BPCompilationUnit.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=BP,NODE_EXTENDS=,NODE_FACTORY= */
package effect.bparser;

public class BPCompilationUnit extends SimpleNode {
  public BPCompilationUnit(int id) {
    super(id);
  }

  public BPCompilationUnit(BParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=bd2ba46c731d35f17bdad95d75ef384b (do not edit this line) */
