/* Generated By:JJTree: Do not edit this line. BPLiteral.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=BP,NODE_EXTENDS=,NODE_FACTORY= */
package effect.bparser;

public class BPLiteral extends SimpleNode {
  public BPLiteral(int id) {
    super(id);
  }

  public BPLiteral(BParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=18d5ba22adfe043506accf891fc02413 (do not edit this line) */
