/* Generated By:JJTree: Do not edit this line. BPLocalVariableDeclaration.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=BP,NODE_EXTENDS=,NODE_FACTORY= */
package effect.bparser;

public class BPLocalVariableDeclaration extends SimpleNode {
  public BPLocalVariableDeclaration(int id) {
    super(id);
  }

  public BPLocalVariableDeclaration(BParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=02b445711eae5324db10336412e2a356 (do not edit this line) */
