/* Generated By:JJTree: Do not edit this line. BPName.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=BP,NODE_EXTENDS=,NODE_FACTORY= */
package effect.bparser;

public class BPName extends SimpleNode {
  public BPName(int id) {
    super(id);
  }

  public BPName(BParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b92209f0f1215d6dccbf152de3c5b897 (do not edit this line) */
