/* Generated By:JJTree: Do not edit this line. BPStatementExpression.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=BP,NODE_EXTENDS=,NODE_FACTORY= */
package effect.bparser;

public class BPStatementExpression extends SimpleNode {
  public BPStatementExpression(int id) {
    super(id);
  }

  public BPStatementExpression(BParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3318d9ccccede69eb4203ed235e3ebba (do not edit this line) */
