/* Generated By:JavaCC: Do not edit this line. JParserTreeConstants.java Version 4.1 */
package effect.jparser;

public interface JParserTreeConstants
{
  public int JJTCOMPILATIONUNIT = 0;
  public int JJTPACKAGEDECLARATION = 1;
  public int JJTVOID = 2;
  public int JJTFIELDDECLARATION = 3;
  public int JJTVARIABLEDECLARATORID = 4;
  public int JJTTYPE = 5;
  public int JJTNAME = 6;
  public int JJTLITERAL = 7;


  public String[] jjtNodeName = {
    "CompilationUnit",
    "PackageDeclaration",
    "void",
    "FieldDeclaration",
    "VariableDeclaratorId",
    "Type",
    "Name",
    "Literal",
  };
}
/* JavaCC - OriginalChecksum=bb9264d13da0048948ef43fdeb3794ad (do not edit this line) */
