/* Generated By:JavaCC: Do not edit this line. JParserVisitor.java Version 4.1 */
package effect.jparser;

public interface JParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(JPCompilationUnit node, Object data);
  public Object visit(JPPackageDeclaration node, Object data);
  public Object visit(JPFieldDeclaration node, Object data);
  public Object visit(JPVariableDeclaratorId node, Object data);
  public Object visit(JPType node, Object data);
  public Object visit(JPName node, Object data);
  public Object visit(JPLiteral node, Object data);
}
/* JavaCC - OriginalChecksum=aa05d01327b95a474ca63fc3e23726a0 (do not edit this line) */
