/* Generated By:JJTree: Do not edit this line. JPFieldDeclaration.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=JP,NODE_EXTENDS=,NODE_FACTORY= */
package effect.jparser;

public class JPFieldDeclaration extends SimpleNode {
  public JPFieldDeclaration(int id) {
    super(id);
  }

  public JPFieldDeclaration(JParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c39fc5335bc1971f8c695c0145d54419 (do not edit this line) */
