/* Generated By:JJTree: Do not edit this line. JPLiteral.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=JP,NODE_EXTENDS=,NODE_FACTORY= */
package effect.jparser;

public class JPLiteral extends SimpleNode {
  public JPLiteral(int id) {
    super(id);
  }

  public JPLiteral(JParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=00e34f1159bb7b7df32142a4279e977f (do not edit this line) */
