/* Generated By:JJTree: Do not edit this line. JPName.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=JP,NODE_EXTENDS=,NODE_FACTORY= */
package effect.jparser;

public class JPName extends SimpleNode {
  public JPName(int id) {
    super(id);
  }

  public JPName(JParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0db9b1cf866d66e7ff64e3a095c8a4dd (do not edit this line) */
