/* Generated By:JJTree: Do not edit this line. JPType.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=JP,NODE_EXTENDS=,NODE_FACTORY= */
package effect.jparser;

public class JPType extends SimpleNode {
  public JPType(int id) {
    super(id);
  }

  public JPType(JParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=7c7b915852799b62d55b7dba0ba7d9be (do not edit this line) */
