/* Generated By:JJTree: Do not edit this line. JPVariableDeclaratorId.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=JP,NODE_EXTENDS=,NODE_FACTORY= */
package effect.jparser;

public class JPVariableDeclaratorId extends SimpleNode {
  public JPVariableDeclaratorId(int id) {
    super(id);
  }

  public JPVariableDeclaratorId(JParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b797d2fab48bad677fa7aee162d95909 (do not edit this line) */
