/* Generated By:JJTree: Do not edit this line. C:\workspace\prime-util\src\effect\jparser\JParserVisitor.java */

package effect.jparser;

public interface JParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(JPCompilationUnit node, Object data);
  public Object visit(JPPackageDeclaration node, Object data);
  public Object visit(JPFieldDeclaration node, Object data);
  public Object visit(JPVariableDeclaratorId node, Object data);
  public Object visit(JPType node, Object data);
  public Object visit(JPName node, Object data);
  public Object visit(JPLiteral node, Object data);
}
