/* Generated By:JJTree: Do not edit this line. ASTLiteral.java */

package effect.jparser;


public class JPLiteral extends SimpleNode {
  public JPLiteral(int id) {
    super(id);
  }

  public JPLiteral(JParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
