/* Generated By:JJTree: Do not edit this line. ASTName.java */

package effect.jparser;


public class JPName extends SimpleNode {
  public JPName(int id) {
    super(id);
  }

  public JPName(JParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  public String toString()
  {
      return "name:" + name;
  }
  
  public String getName()
  {
      return name;
  }
  public void setName(String name)
  {
      this.name = name;
  }

    private String name;  
}
