/* Generated By:JJTree: Do not edit this line. ASTPackageDeclaration.java */

package effect.jparser;


public class JPPackageDeclaration extends SimpleNode {
  public JPPackageDeclaration(int id) {
    super(id);
  }

  public JPPackageDeclaration(JParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
