/* Generated By:JJTree: Do not edit this line. ASTType.java */

package effect.jparser;


public class JPType extends SimpleNode {
  public JPType(int id) {
    super(id);
  }

  public JPType(JParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
public String getName()
{
    return name;
}
public void setName(String name)
{
    this.name = name;
    this.primitive = false;
}

public void setPrimitive()
{
    primitive = true;
}

public boolean isPrimitive()
{
    return primitive;
}

  private String name;
  private boolean primitive = false;
}
