/* Generated By:JJTree: Do not edit this line. C:\workspace\prime-util\src\effect\bparser\BParserTreeConstants.java */

package effect.bparser;

public interface BParserTreeConstants
{
  public int JJTCOMPILATIONUNIT = 0;
  public int JJTVOID = 1;
  public int JJTNAME = 2;
  public int JJTLITERAL = 3;
  public int JJTARGUMENTS = 4;
  public int JJTLOCALVARIABLEDECLARATION = 5;
  public int JJTSTATEMENTEXPRESSION = 6;


  public String[] jjtNodeName = {
    "CompilationUnit",
    "void",
    "Name",
    "Literal",
    "Arguments",
    "LocalVariableDeclaration",
    "StatementExpression",
  };
}
