/* Generated By:JJTree: Do not edit this line. C:\workspace\prime-util\src\effect\bparser\BParserVisitor.java */

package effect.bparser;

public interface BParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(BPCompilationUnit node, Object data);
  public Object visit(BPName node, Object data);
  public Object visit(BPLiteral node, Object data);
  public Object visit(BPArguments node, Object data);
  public Object visit(BPLocalVariableDeclaration node, Object data);
  public Object visit(BPStatementExpression node, Object data);
}
