/* Generated By:JJTree: Do not edit this line. BPLiteral.java */

package effect.bparser;

public class BPLiteral extends SimpleNode {
  public BPLiteral(int id) {
    super(id);
  }

  public BPLiteral(BParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
