/* Generated By:JJTree: Do not edit this line. BPLocalVariableDeclaration.java */

package effect.bparser;

public class BPLocalVariableDeclaration extends SimpleNode {
  public BPLocalVariableDeclaration(int id) {
    super(id);
  }

  public BPLocalVariableDeclaration(BParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
