/* Generated By:JJTree: Do not edit this line. BPName.java */

package effect.bparser;

public class BPName extends SimpleNode {
  public BPName(int id) {
    super(id);
  }

  public BPName(BParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(BParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
